### ISSUE TITLE
When using XMLHttpRequest I run into 'blocked by cors policy'

### ISSUE THREAD

**Issue by 4xk** [SilBoydens/Mee6-api-docs#2]
![image](https://user-images.githubusercontent.com/41323499/59501361-5b8a2080-8e69-11e9-9e12-9a1f9482b37d.png)

It works with postman, but im trying to make a live message/xp counter for a server.

**Comment by SilBoydens** [comment]
Making a live counter that polls to fast will get all your users blocked, if you have it pool at a lower rate then eventually your servers leaderboard will be blocked for "ddos attack".

Pls implement a caching system on your server: if a user request it, then check if you have a recent version and give that, otherwise I'd your local version is to old then let your server get a new version and cache that

**Comment by 4xk** [comment]
Ok, has it already been blocked?
Im currently implementing a cache on the server in hopes that it will work
